# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160122_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.TextField(max_length=300, verbose_name='message'),
        ),
    ]
