# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160122_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='author',
            new_name='authors',
        ),
    ]
