# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20160109_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=500, verbose_name='Comment'),
        ),
    ]
