# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_auto_20160110_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
    ]
