# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='text',
            field=models.CharField(max_length=300, verbose_name='message'),
        ),
    ]
